name: psatm

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.config.os }} 
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: output test
      shell: bash
      run: cd tests; bash test.sh
